# k8s/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base
  - hpa.yaml
  - pdb.yaml

commonLabels:
  environment: production

replicas:
  - name: demo-app
    count: 3

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "200m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "500m"
    target:
      kind: Deployment
      name: demo-app

configMapGenerator:
  - name: demo-app-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=warn

images:
  - name: your-registry/demo-app
    newTag: v1.0.0