apiVersion: v2
name: demo-app
description: A Helm chart for GitOps Demo Application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - demo
  - gitops
  - nodejs
maintainers:
  - name: DevOps Team
    email: devops@example.com
