replicaCount: 3

image:
  tag: "v1.0.0"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

ingress:
  enabled: true
  hosts:
    - host: demo-app.example.com
      paths:
        - path: /
          pathType: Prefix

config:
  nodeEnv: production
  logLevel: warn

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

podDisruptionBudget:
  enabled: true
  minAvailable: 2
