# k8s/overlays/staging/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

commonLabels:
  environment: staging

replicas:
  - name: demo-app
    count: 2

configMapGenerator:
  - name: demo-app-config
    behavior: merge
    literals:
      - NODE_ENV=staging
      - LOG_LEVEL=info

images:
  - name: ghcr.io/fevzitopcu/gitops-demo-app/demo-app
    newTag: staging-v1.0.0